# Gunakan image Node.js sebagai base
FROM node:18-alpine

# Set direktori kerja dalam container
WORKDIR /app

# Salin file package.json dan package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Salin seluruh kode aplikasi
COPY . .

# Pastikan Prisma Client sudah di-generate
RUN npx prisma generate

# Jalankan aplikasi
CMD ["npm", "run", "dev"]

# Expose port untuk akses ke server
EXPOSE 3000
